### PR TITLE
Removed unneeded http response wrapper class

### PR DESCRIPTION
**Pull request by adrianjgeorge**

### CODE REVIEW

**Comment by RackerWilliams** [comment]
What's the issue with the checker servlet response?

**Comment by adrianjgeorge** [comment]
it does nothing, litterally. And while we are still using the crappy response wrapper it is occaisionally the source of unexpected bugs.

**Comment by RackerWilliams** [comment]
As it does nothing it can't possibly be the source of a bug right?  Or am I wrong there?

It's a placeholder for when we handle the response stuff.

**Comment by dmnjohns** [comment]
It's not the source of the bug, but it can cause an issue with poorly written wrappers. *cough*

Also, it adds complexity without a reason for doing so. Consider this -- a developer writes a wrapper that copies all of the data from the wrapped response into its own data collections. Since this operation could be relatively expensive, the developer decides to be clever and write some logic that prevents copying the data from the wrapped response if the wrapped response is already an instance of the wrapper. Say that logic is just a static function that returns the response to be wrapped if it is already an instance of a wrapped response, otherwise construct a new wrapped response that copies everything. Well, if api-checker wraps a request before sending it along, we're always forcing the next guy in the chain who wants to use the clever developer's wrapper to pay the cost of constructing a new wrapper.

**Comment by RackerWilliams** [comment]
So four points:

1.  No it does not add complexity, it's a servlet response.  Use the servlet model treat it as a response nothing changes -- you shouldn't even care or be aware that it's there.
2. The developer is not being clever -- you shouldn't make any assumptions about the request and response that you get -- any filter in the chain may wrap them -- and there's nothing you can do about it.  Api-checker is breaking you today -- and you can change api-checker, but you can't ask folks not to wrap responses and you don't know if they will.
3.  If the developer ever wants to cache data in it's own data structures to prevent recomputing it between filters the correct way to cache it is to save the data is in the request context as a request attribute -- that's what that was built for.  That will always work -- and doesn't even require you wrap anything.
4. When we add response handling to api-checker -- we're going to have to wrap the response -- so you're just delaying the problem -- not fixing it.

Fix the underlying problem -- the buggy wrapper -- you're not going to fix it with this pull request.

**Comment by dmnjohns** [comment]
To be clear, there are two issues. The one with our wrapper in Repose that we've already fixed, and the one that this pull request addresses. Admittedly, the root cause was in the Repose wrapper. All of your points on that are correct, and I don't think anyone disagrees with those.

However, the other issue is with the MutableHttpServletResponse wrapper, which the issue in the Repose wrapper led us to. That's what this pull request is addressing. At present, this empty wrapper provides no value. To be fair, it also doesn't cost much, but it's not free. It adds one more level to the stack when it's used. It adds a class in the heap. It necessarily adds complexity, even if that complexity is generally hidden by the abstractions of the servlet spec. The system itself becomes ever-so-slighty more complex.

Take all of that along with the good practice principles of YAGNI and KISS.

To return to one of your points, I understand that the developer is not being clever. However, the case I gave is exactly what is going on in Repose with both wrappers. That's actually part of the reason we're rewriting our wrappers.

**Comment by RackerWilliams** [comment]
1. There is a value in having the wrapper, it means I don't have to break interfaces when I introduce response handling.  Note that handlers -- the extension mechanism in API Checker depend on the request being wrapped.

2. I don't believe it currently introduces an extra item on the stack -- that only comes into play when you override things.  I believe method tables are used in most implementations.  So there's no real cost difference.

This pull request does not resolve anything.  It introduces a breaking change to the contracts now and another break to the contracts when  result handling is introduced. Now, I'm willing to introduce breaking changes if we need them -- but there is no bug here.  The bug is another system -- this is an exercise in avoidance more than anything else.  Fix the real bug :-)

**Pull request closed without merging**
