### PR TITLE
REP-3603 Updated the Saxon-EE library dependency from v9.4.0.9 to v9.5.1-8.

### PR DESCRIPTION
**Pull request by wdschei**

### CODE REVIEW

**Comment by RackerWilliams** [comment]
Not all of the checks passed on this.  This did not complete because we don't have the latest license installed in Jenkins.  You should have 2 successful checks not just one.

See https://jenkins.openrepose.org/job/api-checker_pull_requests/118/

**Comment by adrianjgeorge** [comment]
I expected those failures, with the new way saxon is packaged you can't use any functionality without the license if you have the ee artifact. This proves it.

**Comment by RackerWilliams** [comment]
No you're confused.  There are two seperate runs -- one that tests path without a license which completed successfully: 

https://jenkins.openrepose.org/job/api-checker-no-saxon_pull-requests/116/

and one that test specific EE functionality specifically -- which failed -- only because the license hasn't been updated.

**Comment by wdschei** [comment]
I just updated the license in the puppets.

**Comment by wdschei** [comment]
Everything worked as it was supposed to in Puppet Librarian land that time.

**Comment by wdschei** [comment]
Retest this please.

**Comment by adrianjgeorge** [comment]
fair enough. seems like we might have a missing case here, but i'm not certain since i don't know api checker's build that well. I would think there'd be a no saxon, a saxon he, and a saxon ee build.

**Comment by RackerWilliams** [comment]
The no-saxon build is essentially means saxon-he :-)  Really should say no-saxon-license instead of no saxon.  api-checker has a strong dependency on Saxon -HE at minimum.

**Comment by wdschei** [comment]
This branch was re-based against master and published as v2.0.0-SNAPSHOT

**Pull request merged**
