### PR TITLE
Upgrade saxon and wadl-tools.

### PR DESCRIPTION
**Pull request by RackerWilliams**
No real changes in WADL tools other that it too now uses the latest
version of saxon. The latest version of saxon contains many bug
fixes!

### CODE REVIEW

**Comment by RackerWilliams** [comment]
Rebased to avoid merge conflicts.

**Comment by dmnjohns** [comment]
New conflicts from the last couple of merges.

**Comment by RackerWilliams** [comment]
Rebased again,  there's always going to be a conflict around the release notes.   I don't mind if you resolve it on merge.

**Comment by dmnjohns** [comment]
Fair enough. I'll start doing that, then.

**Comment by RackerWilliams** [comment]
...just don't mess it up :-D

**Pull request merged**
